#ifndef LOGWINDOW_H
#define LOGWINDOW_H

#include <QWidget>
#include "DatabaseManager.h"

namespace Ui {
class LogWindow;
}

class LogWindow : public QWidget
{
    Q_OBJECT

public:
    explicit LogWindow(QWidget *parent = nullptr);
    ~LogWindow();

private slots:
    void onLoginClicked();

private:
    Ui::LogWindow *ui;  // UI class generated by Qt
};

#endif // LOGWINDOW_H
